theme = "rose_pine_moon"

[editor]
cursorline = true
color-modes = true
auto-save = true
bufferline = "multiple"

[editor.indent-guides]
render = true

[editor.statusline]
left = ["mode"]
center = ["file-name"]
right = ["diagnostics", "selections", "position"]
